app:
  name: postgres
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
  image: ghcr.io/joeckr/postgres
  tag: latest
  pullPolicy: Always
  port: 5432
  db: postgres
  user: postgres
  password: changeme  # betterleaks:allow
  storageAccessMode: ReadWriteOnce
  storageSize: 1Gi
  storageClass: ""
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    fsGroup: 1031 # take this out if deploying to OpenShift
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

initSchema:
  enabled: false
