apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name}}
  labels:
    app: {{ .Values.postgres.app }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.app }}
    spec:
      {{- with .Values.postgres.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        {{- if .Values.initSchema.enabled }}
        - name: postgres-schema
          configMap:
            name: postgres-schema
        {{- end }}
      containers:
        - name: {{ .Values.postgres.name }}
          {{- with .Values.postgres.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag }}"
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
              name: {{ .Values.postgres.name }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /tmp
            {{- if .Values.initSchema.enabled }}
            - name: postgres-schema
              mountPath: /docker-entrypoint-initdb.d/schema.sql
              subPath: schema.sql
            {{- end }}
