apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: {{ .Values.app.name }}
spec:
  accessModes:
    - {{ .Values.app.storageAccessMode }}
  resources:
    requests:
      storage: {{ .Values.app.storageSize }}
  {{- if .Values.app.storageClass }}
  storageClassName: {{ .Values.app.storageClass | quote }}
  {{- end }}
