{{- if .Values.initSchema.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-schema
  labels:
    app: {{ .Values.app.name }}
data:
  schema.sql: |
    {{ .Files.Get (print "config/schema.sql") | nindent 4 }}
{{- end }}
