apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: {{ .Values.app.name }}
  selector:
    app: {{ .Values.app.name }}
